### ISSUE TITLE
Node cannot find server file from packages

### ISSUE THREAD

**Issue by saeidalidadi** [google/boardgame.io#17]
I got `Node` module resolving error as bellow:

```
Error: Cannot find module 'boardgame.io/server'
````

**Comment by xiaoyuhen** [comment]
same problem

**Comment by nicolodavis** [comment]
Actually, this was broken by https://github.com/google/boardgame.io/pull/11 :) Sorry, approved that rather absent mindedly.

**Comment by nicolodavis** [comment]
Should be fixed by #13
